// O acervo da loja, separado do seed.ts para o seed nao virar um arquivo de
// tres mil linhas. Aqui so ficam os produtos; usuarios, pedidos e avaliacoes
// estao no seed.
//
// As fotos vem do Open Library (capas), do Rebrickable (caixas de LEGO) e do
// Wikimedia Commons (o resto). Os creditos estao em
// frontend/public/CREDITOS-IMAGENS.md.
import type { ProductKind } from '@prisma/client'

export interface SeedProduct {
  slug: string
  title: string
  kind: ProductKind
  price: number
  /** Preço de tabela, só quando o produto está mesmo em promoção. */
  compareAtPrice?: number
  stock: number
  /** Caminho relativo dentro de `frontend/public/img/`. */
  image: string
  genre: string
  synopsis: string
  excerpt?: string
  brand?: string
  house?: 'grifinoria' | 'sonserina' | 'corvinal' | 'lufa-lufa'
  character?: string
  tags?: string[]
  /** Produto com ficha bibliográfica: autora, editora e ISBN. */
  biblio?: boolean
  isbn?: string
  pages?: number
  publishedAt?: string
  featured?: boolean
}

const ROCCO = 'Rocco'
const NOBLE = 'Noble Collection'
const LEGO = 'LEGO'
const CINEREPLICAS = 'Cinereplicas'
const FUNKO = 'Funko'
const PALADONE = 'Paladone'

// ===== Livros =====

const SAGA: SeedProduct[] = [
  {
    slug: 'harry-potter-e-a-pedra-filosofal',
    title: 'Harry Potter e a Pedra Filosofal',
    kind: 'BOOK',
    isbn: '9788532530783',
    price: 44.9,
    compareAtPrice: 59.9,
    stock: 120,
    image: 'books/pedra-filosofal.webp',
    genre: 'Fantasia',
    pages: 264,
    publishedAt: '1997-06-26',
    featured: true,
    biblio: true,
    brand: ROCCO,
    character: 'Harry Potter',
    tags: ['saga', 'mais-vendido', 'presente'],
    synopsis:
      'A vida do menino Harry Potter não tem um pingo de magia. Ele vive com os tios e o primo, que não gostam nem um pouco dele. O quarto de Harry é, na verdade, um armário sob a escada, e ele nunca comemorou um aniversário sequer em onze anos. Até que, um dia, Harry recebe uma carta misteriosa, entregue por uma coruja: um convite para estudar num lugar incrível chamado Escola de Magia e Bruxaria Hogwarts.',
    excerpt:
      '"O senhor é um bruxo, Harry." Foi assim, numa cabana no meio do mar, que o menino descobriu quem sempre tinha sido.',
  },
  {
    slug: 'harry-potter-e-a-camara-secreta',
    title: 'Harry Potter e a Câmara Secreta',
    kind: 'BOOK',
    isbn: '9788532511010',
    price: 44.9,
    stock: 98,
    image: 'books/camara-secreta.webp',
    genre: 'Fantasia',
    pages: 288,
    publishedAt: '1998-07-02',
    biblio: true,
    brand: ROCCO,
    character: 'Harry Potter',
    tags: ['saga'],
    synopsis:
      'De volta a Hogwarts para o segundo ano, Harry começa a ouvir uma voz que ninguém mais escuta e mensagens aparecem escritas nas paredes do castelo. A lenda da Câmara Secreta, aberta por um herdeiro de Sonserina, deixa de ser história antiga quando os alunos começam a ser petrificados um a um.',
    excerpt:
      'São as nossas escolhas, Harry, que revelam o que realmente somos, muito mais do que as nossas qualidades.',
  },
  {
    slug: 'harry-potter-e-o-prisioneiro-de-azkaban',
    title: 'Harry Potter e o Prisioneiro de Azkaban',
    kind: 'BOOK',
    isbn: '9788532511386',
    price: 47.9,
    stock: 86,
    image: 'books/prisioneiro-de-azkaban.webp',
    genre: 'Fantasia',
    pages: 352,
    publishedAt: '1999-07-08',
    biblio: true,
    brand: ROCCO,
    character: 'Sirius Black',
    tags: ['saga', 'mais-vendido'],
    synopsis:
      'Sirius Black fugiu de Azkaban e, segundo dizem, vem atrás de Harry. Dementadores cercam a escola, o passado dos pais de Harry volta à tona e um mapa antigo mostra que nem tudo em Hogwarts é o que parece. Um livro sobre tempo, medo e sobre aprender a conjurar a própria luz.',
    excerpt:
      'A felicidade pode ser encontrada mesmo nas horas mais sombrias, se a pessoa lembrar de acender a luz.',
  },
  {
    slug: 'harry-potter-e-o-calice-de-fogo',
    title: 'Harry Potter e o Cálice de Fogo',
    kind: 'BOOK',
    isbn: '9788532512819',
    price: 54.9,
    stock: 74,
    image: 'books/calice-de-fogo.webp',
    genre: 'Fantasia',
    pages: 640,
    publishedAt: '2000-07-08',
    featured: true,
    biblio: true,
    brand: ROCCO,
    character: 'Harry Potter',
    tags: ['saga'],
    synopsis:
      'Hogwarts recebe o Torneio Tribruxo e, com ele, delegações de outras escolas de magia. O Cálice de Fogo escolhe três campeões e, contra todas as regras, cospe um quarto nome: Harry Potter. Entre dragões, sereianos e um labirinto, o ano em que a infância termina.',
    excerpt: 'Vem aí um tempo em que teremos de escolher entre o que é certo e o que é fácil.',
  },
  {
    slug: 'harry-potter-e-a-ordem-da-fenix',
    title: 'Harry Potter e a Ordem da Fênix',
    kind: 'BOOK',
    isbn: '9788532517814',
    price: 57.9,
    stock: 61,
    image: 'books/ordem-da-fenix.jpg',
    genre: 'Fantasia',
    pages: 704,
    publishedAt: '2003-06-21',
    biblio: true,
    brand: ROCCO,
    character: 'Harry Potter',
    tags: ['saga'],
    synopsis:
      'Ninguém acredita em Harry quando ele diz que Voldemort voltou. O Ministério ocupa Hogwarts, a escola vira um lugar hostil e um grupo de alunos decide aprender a se defender por conta própria. O livro mais longo e mais raivoso da saga, e também o mais sobre luto.',
    excerpt: 'Nós temos algo que Voldemort não tem: algo pelo que vale a pena lutar.',
  },
  {
    slug: 'harry-potter-e-o-enigma-do-principe',
    title: 'Harry Potter e o Enigma do Príncipe',
    kind: 'BOOK',
    isbn: '9788532519788',
    price: 52.9,
    stock: 80,
    image: 'books/enigma-do-principe.webp',
    genre: 'Fantasia',
    pages: 528,
    publishedAt: '2005-07-16',
    featured: true,
    biblio: true,
    brand: ROCCO,
    character: 'Severo Snape',
    tags: ['saga'],
    synopsis:
      'O mundo bruxo já não finge que está tudo bem: Voldemort agiu à luz do dia e o medo voltou a atravessar as ruas. Em Hogwarts, Harry recebe um livro de Poções cheio de anotações de um antigo aluno que assina como Príncipe Mestiço, e passa o ano dividido entre as aulas particulares de Dumbledore e a lembrança de um garoto chamado Tom Riddle.',
    excerpt:
      'É preciso muita coragem para enfrentar os inimigos, mas é preciso ainda mais para enfrentar os amigos.',
  },
  {
    slug: 'harry-potter-e-as-reliquias-da-morte',
    title: 'Harry Potter e as Relíquias da Morte',
    kind: 'BOOK',
    isbn: '9788532522504',
    price: 57.9,
    stock: 66,
    image: 'books/reliquias-da-morte.jpg',
    genre: 'Fantasia',
    pages: 592,
    publishedAt: '2007-07-21',
    biblio: true,
    brand: ROCCO,
    character: 'Harry Potter',
    tags: ['saga', 'mais-vendido'],
    synopsis:
      'Sem escola, sem professores e sem um plano completo, Harry, Rony e Hermione saem à caça das Horcruxes. O desfecho cobra o preço de tudo o que veio antes e responde à pergunta que a saga vinha fazendo desde a primeira carta: o que fazer com a morte.',
    excerpt:
      'Não tenha pena dos mortos, Harry. Tenha pena dos vivos e, acima de tudo, daqueles que vivem sem amor.',
  },
]

const COMPLEMENTARES: SeedProduct[] = [
  {
    slug: 'harry-potter-e-a-crianca-amaldicoada',
    title: 'Harry Potter e a Criança Amaldiçoada',
    kind: 'BOOK',
    isbn: '9788532530127',
    price: 39.9,
    stock: 70,
    image: 'books/crianca-amaldicoada.jpg',
    genre: 'Teatro',
    pages: 336,
    publishedAt: '2016-07-31',
    biblio: true,
    brand: ROCCO,
    character: 'Alvo Potter',
    tags: ['oitava-historia'],
    synopsis:
      'A oitava história, em forma de peça de teatro. Dezenove anos depois, Harry é funcionário do Ministério, pai de três filhos e nada bom em ser pai do do meio. Alvo Severo carrega um nome pesado demais para um menino, e um vira-tempo esquecido dá a ele a chance de mexer no que não devia.',
    excerpt: 'O amor nos torna cegos. Nós dois tentamos dar aos nossos filhos não o que eles precisavam.',
  },
  {
    slug: 'crianca-amaldicoada-a-jornada',
    title: 'A Criança Amaldiçoada: A Jornada',
    kind: 'BOOK',
    price: 89.9,
    stock: 26,
    image: 'books/crianca-amaldicoada-jornada.jpg',
    genre: 'Bastidores',
    pages: 208,
    publishedAt: '2017-11-14',
    biblio: true,
    brand: ROCCO,
    tags: ['bastidores'],
    synopsis:
      'Os bastidores da peça mais premiada do West End: os cadernos dos figurinistas, as maquetes de cenário, os truques de palco que fazem uma pessoa entrar numa lareira e sair na outra ponta. Um livro sobre como se constrói magia sem efeito digital nenhum.',
  },
  {
    slug: 'os-contos-de-beedle-o-bardo',
    title: 'Os Contos de Beedle, o Bardo',
    kind: 'BOOK',
    isbn: '9788532525345',
    price: 34.9,
    stock: 90,
    image: 'books/contos-de-beedle.jpg',
    genre: 'Contos',
    pages: 120,
    publishedAt: '2008-12-04',
    biblio: true,
    brand: ROCCO,
    character: 'Alvo Dumbledore',
    tags: ['biblioteca-de-hogwarts'],
    synopsis:
      'Cinco contos que toda criança bruxa ouve antes de dormir, com os comentários de Alvo Dumbledore em nota de rodapé, inclusive o conto dos três irmãos, que só na sétima parte da saga revela o que sempre esteve dizendo.',
    excerpt: 'Era uma vez três irmãos que viajavam por uma estrada solitária e sinuosa ao anoitecer.',
  },
  {
    slug: 'quadribol-atraves-dos-seculos',
    title: 'Quadribol Através dos Séculos',
    kind: 'BOOK',
    isbn: '9788532511997',
    price: 29.9,
    stock: 88,
    image: 'books/quadribol-atraves-dos-seculos.jpg',
    genre: 'Esporte',
    pages: 96,
    publishedAt: '2001-03-01',
    biblio: true,
    brand: ROCCO,
    tags: ['biblioteca-de-hogwarts', 'quadribol'],
    synopsis:
      'O livro que fica na biblioteca de Hogwarts e nunca está na estante. A história do esporte desde as vassouras medievais, as setecentas faltas possíveis e por que o pomo de ouro substituiu um pobre pássaro de verdade.',
  },
  {
    slug: 'animais-fantasticos-e-onde-habitam',
    title: 'Animais Fantásticos e Onde Habitam',
    kind: 'BOOK',
    isbn: '9788532511994',
    price: 32.9,
    stock: 84,
    image: 'books/animais-fantasticos.jpg',
    genre: 'Guia',
    pages: 128,
    publishedAt: '2001-03-01',
    biblio: true,
    brand: ROCCO,
    character: 'Newt Scamander',
    tags: ['biblioteca-de-hogwarts'],
    synopsis:
      'O manual de Newt Scamander: setenta e cinco criaturas mágicas classificadas pela quantidade de bruxos que já mataram. Traz as anotações que Harry, Rony e Hermione deixaram nas margens do exemplar da escola.',
  },
  {
    slug: 'animais-fantasticos-roteiro-original',
    title: 'Animais Fantásticos: o roteiro original',
    kind: 'BOOK',
    price: 44.9,
    stock: 52,
    image: 'books/animais-fantasticos-roteiro.jpg',
    genre: 'Roteiro',
    pages: 304,
    publishedAt: '2016-11-18',
    biblio: true,
    brand: ROCCO,
    character: 'Newt Scamander',
    synopsis:
      'Nova York, 1926. Um magizoologista britânico desembarca com uma mala que não deveria abrir sozinha, e abre. O primeiro roteiro escrito por J. K. Rowling, publicado como se lê uma peça: rubricas, silêncios e tudo.',
  },
  {
    slug: 'biblioteca-de-hogwarts-caixa',
    title: 'A Biblioteca de Hogwarts: caixa com 3 livros',
    kind: 'BOX_SET',
    price: 89.9,
    compareAtPrice: 109.9,
    stock: 40,
    image: 'books/biblioteca-de-hogwarts.jpg',
    genre: 'Coleção',
    pages: 344,
    biblio: true,
    brand: ROCCO,
    featured: true,
    tags: ['presente', 'biblioteca-de-hogwarts'],
    synopsis:
      'Os três livros da biblioteca da escola numa caixa só: Quadribol Através dos Séculos, Animais Fantásticos e Onde Habitam e Os Contos de Beedle, o Bardo. É o presente certo para quem já leu a saga inteira e quer voltar por outra porta.',
  },
  {
    slug: 'harry-potter-uma-historia-da-magia',
    title: 'Harry Potter: Uma História da Magia',
    kind: 'BOOK',
    price: 119.9,
    stock: 30,
    image: 'books/historia-da-magia.jpg',
    genre: 'Bastidores',
    pages: 256,
    publishedAt: '2017-10-20',
    biblio: true,
    brand: ROCCO,
    tags: ['bastidores', 'presente'],
    synopsis:
      'O catálogo da exposição da Biblioteca Britânica: manuscritos de alquimia, mapas de sereias, um caldeirão de bronze do século XIV e os rascunhos da própria autora lado a lado com a magia que os inspirou.',
  },
  {
    slug: 'uma-jornada-pela-historia-da-magia',
    title: 'Uma Jornada pela História da Magia',
    kind: 'BOOK',
    price: 54.9,
    stock: 44,
    image: 'books/jornada-historia-da-magia.jpg',
    genre: 'Bastidores',
    pages: 128,
    publishedAt: '2018-10-04',
    biblio: true,
    brand: ROCCO,
    synopsis:
      'A versão de bolso da exposição: as mesmas seis matérias de Hogwarts (Poções, Herbologia, Astronomia, Adivinhação, Trato das Criaturas e Defesa), cada uma com a magia real que existiu antes da magia inventada.',
  },
  {
    slug: 'harry-potter-o-livro-de-receitas',
    title: 'O Livro de Receitas do Mundo Bruxo',
    kind: 'BOOK',
    price: 79.9,
    stock: 48,
    image: 'books/livro-de-receitas.jpg',
    genre: 'Culinária',
    pages: 192,
    biblio: true,
    tags: ['presente', 'novidade'],
    synopsis:
      'Quarenta e três receitas do banquete do Salão Principal à mesa da sua casa: torta de melaço, cerveja amanteigada quente, o pudim de Natal dos Weasley e o café da manhã que aparece sozinho nos pratos.',
  },
  {
    slug: 'livro-de-colorir-magico',
    title: 'Livro de Colorir Mágico',
    kind: 'BOOK',
    price: 49.9,
    stock: 65,
    image: 'books/livro-de-colorir.jpg',
    genre: 'Atividades',
    pages: 96,
    tags: ['presente'],
    synopsis:
      'Noventa e seis páginas de arte de linha tirada dos filmes, em papel gramatura alta que aguenta caneta de ponta grossa. O Beco Diagonal, o Salão Principal e um hipogrifo esperando a sua paleta.',
  },
  {
    slug: 'harry-potter-page-to-screen',
    title: 'Harry Potter: Page to Screen',
    kind: 'BOOK',
    price: 249.9,
    stock: 12,
    image: 'books/page-to-screen.jpg',
    genre: 'Bastidores',
    pages: 532,
    biblio: true,
    tags: ['colecionador'],
    synopsis:
      'O tijolo definitivo sobre os oito filmes: 532 páginas de arte conceitual, plantas de cenário, provas de figurino e entrevistas com a equipe inteira. Pesa quatro quilos e não cabe em estante rasa.',
  },
  {
    slug: 'harry-potter-film-wizardry',
    title: 'Harry Potter Film Wizardry',
    kind: 'BOOK',
    price: 159.9,
    stock: 18,
    image: 'books/film-wizardry.jpg',
    genre: 'Bastidores',
    pages: 160,
    biblio: true,
    tags: ['colecionador'],
    synopsis:
      'Um livro com bolsos: réplicas destacáveis de cartazes do Ministério, cardápio do Salão Principal, panfleto do Torneio Tribruxo. Feito para ser aberto devagar, não lido de uma vez.',
  },
  {
    slug: 'os-mundos-magicos-de-harry-potter',
    title: 'Os Mundos Mágicos de Harry Potter',
    kind: 'BOOK',
    price: 42.9,
    stock: 55,
    image: 'books/mundos-magicos.jpg',
    genre: 'Ensaio',
    pages: 288,
    biblio: true,
    synopsis:
      'De onde vem cada criatura, cada feitiço e cada nome da saga. Um passeio pela mitologia, pela alquimia e pelo folclore que Rowling reaproveitou, e um bom argumento para quem gosta de discutir tradução no jantar.',
  },
  {
    slug: 'o-companheiro-do-feiticeiro',
    title: 'O Companheiro do Feiticeiro',
    kind: 'BOOK',
    price: 46.9,
    stock: 42,
    image: 'books/companheiro-do-feiticeiro.jpg',
    genre: 'Ensaio',
    pages: 384,
    biblio: true,
    synopsis:
      'Um dicionário do mundo bruxo em ordem alfabética, de Abraxan a Zumbi. Serve para consulta rápida no meio da releitura e para resolver discussão de mesa sobre quem inventou o quê.',
  },
  {
    slug: 'livros-didaticos-de-hogwarts',
    title: 'Os livros didáticos de Hogwarts: caixa dupla',
    kind: 'BOX_SET',
    price: 59.9,
    stock: 36,
    image: 'books/livros-didaticos.jpg',
    genre: 'Coleção',
    pages: 224,
    biblio: true,
    brand: ROCCO,
    synopsis:
      'Animais Fantásticos e Quadribol Através dos Séculos na caixa dupla original, do jeito que foram vendidos em 2001 para financiar a Comic Relief. Dois livros finos, uma boa história por trás.',
  },
]

const CAIXAS: SeedProduct[] = [
  {
    slug: 'colecao-completa-sete-volumes',
    title: 'Coleção Harry Potter: sete volumes',
    kind: 'BOX_SET',
    isbn: '9788532530790',
    price: 329.9,
    compareAtPrice: 399.9,
    stock: 34,
    image: 'books/serie-completa.jpg',
    genre: 'Coleção',
    pages: 3407,
    biblio: true,
    brand: ROCCO,
    featured: true,
    tags: ['presente', 'mais-vendido'],
    synopsis:
      'Os sete anos em Hogwarts numa caixa só, nas edições brasileiras da Rocco. É a saga inteira, do armário sob a escada ao duelo final, com as lombadas formando um desenho maior quando os livros ficam lado a lado na estante.',
  },
  {
    slug: 'caixa-primeiros-anos',
    title: 'Caixa Hogwarts: os três primeiros anos',
    kind: 'BOX_SET',
    price: 129.9,
    stock: 44,
    image: 'books/pedra-filosofal-italiana.jpg',
    genre: 'Coleção',
    pages: 904,
    biblio: true,
    brand: ROCCO,
    tags: ['presente'],
    synopsis:
      'A Pedra Filosofal, a Câmara Secreta e o Prisioneiro de Azkaban: os três livros em que Hogwarts ainda é, sobretudo, uma escola. A porta de entrada mais comum para quem vai começar a saga agora.',
  },
]

const EDICOES: SeedProduct[] = [
  {
    slug: 'pedra-filosofal-edicao-ilustrada',
    title: 'A Pedra Filosofal: Edição Ilustrada por Jim Kay',
    kind: 'SPECIAL_EDITION',
    price: 169.9,
    compareAtPrice: 199.9,
    stock: 38,
    image: 'books/pedra-filosofal-ilustrada.jpg',
    genre: 'Edição especial',
    pages: 256,
    biblio: true,
    brand: ROCCO,
    featured: true,
    tags: ['ilustrada', 'presente'],
    synopsis:
      'O primeiro ano em formato grande, capa dura e uma ilustração de Jim Kay em cada abertura de capítulo. É o mesmo texto que todo mundo conhece, num objeto feito para ficar aberto sobre a mesa em vez de guardado na estante.',
  },
  {
    slug: 'camara-secreta-edicao-ilustrada',
    title: 'A Câmara Secreta: Edição Ilustrada por Jim Kay',
    kind: 'SPECIAL_EDITION',
    price: 169.9,
    stock: 32,
    image: 'books/camara-secreta-jim-kay.jpg',
    genre: 'Edição especial',
    pages: 264,
    biblio: true,
    brand: ROCCO,
    tags: ['ilustrada'],
    synopsis:
      'O segundo ano ilustrado, com a Aranha Aragogue ocupando duas páginas inteiras e um basilisco que dá vontade de fechar o livro. Capa dura, papel couché e cabeçado na lombada.',
  },
  {
    slug: 'azkaban-edicao-ilustrada',
    title: 'O Prisioneiro de Azkaban: Edição Ilustrada',
    kind: 'SPECIAL_EDITION',
    price: 179.9,
    stock: 28,
    image: 'books/azkaban-jim-kay.jpg',
    genre: 'Edição especial',
    pages: 336,
    biblio: true,
    brand: ROCCO,
    tags: ['ilustrada'],
    synopsis:
      'O ano do bicho-papão, do mapa e do patrono, ilustrado em cores que vão escurecendo de capítulo em capítulo. A cena do lago, na página 300, vende o livro sozinha.',
  },
  {
    slug: 'calice-de-fogo-edicao-ilustrada',
    title: 'O Cálice de Fogo: Edição Ilustrada',
    kind: 'SPECIAL_EDITION',
    price: 199.9,
    stock: 24,
    image: 'books/calice-de-fogo-jim-kay.jpg',
    genre: 'Edição especial',
    pages: 464,
    biblio: true,
    brand: ROCCO,
    tags: ['ilustrada', 'novidade'],
    synopsis:
      'O maior dos volumes ilustrados até aqui: o rabo-córneo-húngaro, o baile de inverno e o cemitério, todos em página dupla. Vem com sobrecapa e miolo costurado.',
  },
  {
    slug: 'pedra-filosofal-edicao-pop-up',
    title: 'Hogwarts: livro pop-up com páginas em 3D',
    kind: 'SPECIAL_EDITION',
    price: 289.9,
    stock: 16,
    image: 'books/pop-up-hogwarts.jpg',
    genre: 'Edição especial',
    pages: 32,
    biblio: true,
    featured: true,
    tags: ['pop-up', 'presente', 'novidade'],
    synopsis:
      'Seis cenários que se levantam da página quando você abre o livro: o castelo inteiro, o Salão Principal com as velas suspensas, o campo de quadribol, o Beco Diagonal, a Floresta Proibida e a plataforma nove e meia. Engenharia de papel de verdade: não é ilustração, é arquitetura.',
    excerpt: 'Abra na página do Salão Principal e as quatro mesas se erguem, uma de cada vez.',
  },
  {
    slug: 'pedra-filosofal-edicao-grifinoria',
    title: 'A Pedra Filosofal: Edição Grifinória',
    kind: 'SPECIAL_EDITION',
    house: 'grifinoria',
    price: 89.9,
    stock: 35,
    image: 'products/estandarte-grifinoria.jpg',
    genre: 'Edição especial',
    pages: 264,
    biblio: true,
    brand: ROCCO,
    tags: ['casa'],
    synopsis:
      'Edição comemorativa vestida de Grifinória: capa dura em bordô e ouro, brasão em relevo e um caderno final sobre a casa da coragem: quem entrou nela, o que a define e por que o Chapéu hesita tanto diante de alguns alunos.',
  },
  {
    slug: 'pedra-filosofal-edicao-sonserina',
    title: 'A Pedra Filosofal: Edição Sonserina',
    kind: 'SPECIAL_EDITION',
    house: 'sonserina',
    price: 89.9,
    stock: 35,
    image: 'products/estandarte-sonserina.jpg',
    genre: 'Edição especial',
    pages: 264,
    biblio: true,
    brand: ROCCO,
    tags: ['casa'],
    synopsis:
      'Edição comemorativa vestida de Sonserina: capa dura em verde e prata, brasão em relevo e um caderno final sobre a casa da ambição, a mais mal compreendida das quatro, e a que mais rende discussão entre leitores.',
  },
  {
    slug: 'pedra-filosofal-edicao-corvinal',
    title: 'A Pedra Filosofal: Edição Corvinal',
    kind: 'SPECIAL_EDITION',
    house: 'corvinal',
    price: 89.9,
    stock: 35,
    image: 'products/estandarte-corvinal.jpg',
    genre: 'Edição especial',
    pages: 264,
    biblio: true,
    brand: ROCCO,
    tags: ['casa'],
    synopsis:
      'Edição comemorativa vestida de Corvinal: capa dura em azul e bronze, brasão em relevo e um caderno final sobre a casa da sabedoria, com as charadas que a aldrava da Torre faz a quem quer entrar.',
  },
  {
    slug: 'pedra-filosofal-edicao-lufa-lufa',
    title: 'A Pedra Filosofal: Edição Lufa-Lufa',
    kind: 'SPECIAL_EDITION',
    house: 'lufa-lufa',
    price: 89.9,
    stock: 35,
    image: 'products/estandarte-lufa-lufa.jpg',
    genre: 'Edição especial',
    pages: 264,
    biblio: true,
    brand: ROCCO,
    tags: ['casa'],
    synopsis:
      'Edição comemorativa vestida de Lufa-Lufa: capa dura em amarelo e preto, brasão em relevo e um caderno final sobre a casa da lealdade, a que menos aparece nos livros e a que mais gente diz querer para si.',
  },
  {
    slug: 'camara-secreta-edicao-espanhola',
    title: 'A Câmara Secreta: edição de capa dura',
    kind: 'SPECIAL_EDITION',
    price: 99.9,
    stock: 30,
    image: 'books/camara-secreta-ilustrada.jpg',
    genre: 'Edição especial',
    pages: 288,
    biblio: true,
    brand: ROCCO,
    synopsis:
      'A mesma tradução de sempre em capa dura com sobrecapa, papel pólen e lombada costurada. Para quem já gastou o exemplar de bolso de tanto reler.',
  },
  {
    slug: 'calice-de-fogo-edicao-de-luxo',
    title: 'O Cálice de Fogo: edição de luxo',
    kind: 'SPECIAL_EDITION',
    price: 109.9,
    stock: 22,
    image: 'books/calice-de-fogo-espanhol.jpg',
    genre: 'Edição especial',
    pages: 640,
    biblio: true,
    brand: ROCCO,
    synopsis:
      'Capa dura, corte pintado em dourado e marcador de fita. O volume mais grosso da saga ganha o acabamento que merece, e ainda abre sem rachar a lombada.',
  },
  {
    slug: 'azkaban-edicao-comemorativa',
    title: 'O Prisioneiro de Azkaban: edição comemorativa',
    kind: 'SPECIAL_EDITION',
    price: 94.9,
    stock: 26,
    image: 'books/azkaban-catalao.jpg',
    genre: 'Edição especial',
    pages: 352,
    biblio: true,
    brand: ROCCO,
    synopsis:
      'Vinte anos do terceiro livro, marcados com nova capa, guardas ilustradas e um posfácio sobre por que este é o volume preferido de tanta gente que leu a saga inteira.',
  },
]

// ===== Varinhas =====

const VARINHAS: SeedProduct[] = [
  {
    slug: 'varinha-de-harry-potter',
    title: 'Varinha de Harry Potter',
    kind: 'WAND',
    price: 249.9,
    compareAtPrice: 299.9,
    stock: 55,
    image: 'products/varinha-harry.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    house: 'grifinoria',
    character: 'Harry Potter',
    featured: true,
    tags: ['mais-vendido', 'presente'],
    synopsis:
      'Azevinho e pena de fênix, 28 centímetros, boa flexibilidade. Réplica em resina de 36 cm com acabamento de madeira e o cabo trabalhado, na caixa de colecionador com a etiqueta de Olivaras. Não faz magia; faz um bom peso de papel e um ótimo presente.',
    excerpt: 'A varinha escolhe o bruxo, meu caro Potter. Nunca foi muito claro o porquê.',
  },
  {
    slug: 'varinha-de-hermione-granger',
    title: 'Varinha de Hermione Granger',
    kind: 'WAND',
    price: 239.9,
    stock: 48,
    image: 'products/varinha-hermione.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    house: 'grifinoria',
    character: 'Hermione Granger',
    tags: ['mais-vendido'],
    synopsis:
      'Videira e corda de coração de dragão, 27 centímetros. Réplica em resina de 36 cm com a espiral esculpida no cabo, em caixa de colecionador. Para quem lê com o dedo marcando a página e discute a tradução na mesa do jantar.',
  },
  {
    slug: 'varinha-de-rony-weasley',
    title: 'Varinha de Rony Weasley',
    kind: 'WAND',
    price: 229.9,
    stock: 44,
    image: 'products/varinha-ron.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    house: 'grifinoria',
    character: 'Rony Weasley',
    synopsis:
      'Salgueiro e pelo de unicórnio, 36 centímetros. A segunda varinha do Rony: a primeira, herdada do irmão, terminou partida ao meio dentro do Salgueiro Lutador. Réplica em caixa de colecionador.',
  },
  {
    slug: 'varinha-das-varinhas',
    title: 'A Varinha das Varinhas',
    kind: 'WAND',
    price: 329.9,
    stock: 20,
    image: 'products/varinha-sabugueiro.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    character: 'Alvo Dumbledore',
    featured: true,
    tags: ['colecionador', 'presente'],
    synopsis:
      'Sabugueiro e pelo da cauda de um testrálio, 38 centímetros. A mais poderosa das três Relíquias, com os nós característicos ao longo do corpo. Edição numerada, em caixa de colecionador com base de exposição.',
    excerpt: 'Ela é a mais poderosa varinha que existe. E é sempre a varinha de quem venceu o dono anterior.',
  },
  {
    slug: 'varinha-de-voldemort',
    title: 'Varinha de Lorde Voldemort',
    kind: 'WAND',
    price: 279.9,
    stock: 26,
    image: 'products/varinha-voldemort.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    house: 'sonserina',
    character: 'Lorde Voldemort',
    tags: ['colecionador'],
    synopsis:
      'Teixo e pena de fênix, 33 centímetros e meio, a irmã da varinha de Harry, feita com a pena da mesma ave. Réplica com o punho em forma de garra e acabamento em osso.',
  },
  {
    slug: 'varinha-de-severo-snape',
    title: 'Varinha de Severo Snape',
    kind: 'WAND',
    price: 249.9,
    stock: 30,
    image: 'products/varinha-snape.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    house: 'sonserina',
    character: 'Severo Snape',
    synopsis:
      'Corpo escuro, liso, sem ornamento nenhum, como o dono. Réplica em resina de 36 cm, em caixa de colecionador. A varinha de quem passou dezessete anos fingindo estar do outro lado.',
  },
  {
    slug: 'varinha-de-grindelwald',
    title: 'Varinha de Gellert Grindelwald',
    kind: 'WAND',
    price: 289.9,
    stock: 18,
    image: 'products/varinha-grindelwald.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    character: 'Gellert Grindelwald',
    tags: ['colecionador'],
    synopsis:
      'A varinha do bruxo das trevas anterior a Voldemort, com o corpo de osso claro e a espiral no punho. Réplica em caixa de colecionador, a mesma que passou de mão em mão até chegar em Dumbledore.',
  },
  {
    slug: 'varinhas-de-draco-e-bellatrix',
    title: 'Duo Malfoy: varinhas de Draco e Bellatrix',
    kind: 'WAND',
    price: 429.9,
    compareAtPrice: 499.8,
    stock: 14,
    image: 'products/varinhas-draco-bellatrix.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    house: 'sonserina',
    character: 'Draco Malfoy',
    tags: ['presente'],
    synopsis:
      'As duas varinhas da família em uma caixa dupla: a de espinheiro-alvar do Draco, que Harry acaba ganhando no duelo, e a de nogueira da Bellatrix, com o cabo trabalhado como osso torcido.',
  },
  {
    slug: 'varinhas-da-lufa-lufa',
    title: 'Trio Lufa-Lufa: varinhas da casa',
    kind: 'WAND',
    price: 399.9,
    stock: 16,
    image: 'products/varinhas-lufa-lufa.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    house: 'lufa-lufa',
    synopsis:
      'As varinhas de Cedrico Diggory, Nymphadora Tonks e Newt Scamander numa caixa de três. A casa que menos aparece nos livros tem os três donos de varinha mais interessantes da coleção.',
  },
  {
    slug: 'varinha-com-lumos',
    title: 'Varinha com Lumos: ponta que acende',
    kind: 'WAND',
    price: 199.9,
    stock: 60,
    image: 'products/varinha-lumos.jpg',
    genre: 'Varinha',
    brand: CINEREPLICAS,
    tags: ['novidade', 'presente'],
    synopsis:
      'Aperte o botão escondido no cabo e a ponta acende de verdade, com LED quente, duas pilhas AAA inclusas. É a varinha que as crianças pedem e a que os adultos usam para achar a fechadura no escuro.',
  },
  {
    slug: 'caixa-de-olivaras',
    title: 'Caixa de Olivaras: varinha misteriosa',
    kind: 'WAND',
    price: 179.9,
    stock: 72,
    image: 'products/loja-olivaras.jpg',
    genre: 'Varinha',
    brand: NOBLE,
    featured: true,
    tags: ['novidade', 'presente'],
    synopsis:
      'Você não escolhe: a caixa vem lacrada e a varinha lá dentro é uma das doze do catálogo, sorteada na expedição. É assim que funciona na loja do Beco Diagonal, e é assim que funciona aqui.',
    excerpt: 'Fabricantes de varinhas finas desde 382 a.C.',
  },
]

// ===== Colecionáveis e réplicas =====

const COLECIONAVEIS: SeedProduct[] = [
  {
    slug: 'vira-tempo',
    title: 'Vira-Tempo',
    kind: 'COLLECTIBLE',
    price: 219.9,
    stock: 34,
    image: 'products/vira-tempo.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    character: 'Hermione Granger',
    featured: true,
    tags: ['mais-vendido', 'presente'],
    synopsis:
      'Réplica em metal banhado a ouro das ampulhetas do Ministério, com os dois aros que giram de verdade e a ampulheta de vidro no centro. Vem com corrente de 60 cm e caixa forrada em veludo.',
    excerpt: 'Coisas terríveis acontecem com os bruxos que mexem com o tempo, Harry.',
  },
  {
    slug: 'vira-tempo-colar',
    title: 'Vira-Tempo: versão colar',
    kind: 'COLLECTIBLE',
    price: 149.9,
    stock: 48,
    image: 'products/vira-tempo-joia.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    character: 'Hermione Granger',
    synopsis:
      'A mesma ampulheta em escala menor, feita para usar todo dia: aros em latão dourado, 3,5 cm de diâmetro e corrente fina. Não recomendamos girar três vezes antes de uma prova.',
  },
  {
    slug: 'vira-tempo-caixa-de-colecionador',
    title: 'Vira-Tempo: caixa de colecionador',
    kind: 'COLLECTIBLE',
    price: 329.9,
    stock: 12,
    image: 'products/vira-tempo-caixa.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    tags: ['colecionador'],
    synopsis:
      'Edição numerada com base de madeira, cúpula de vidro e certificado. A ampulheta fica suspensa no ar dentro da redoma. É o objeto mais bonito desta prateleira e o mais difícil de repor.',
  },
  {
    slug: 'medalhao-de-salazar-sonserina',
    title: 'Medalhão de Salazar Sonserina',
    kind: 'COLLECTIBLE',
    price: 189.9,
    stock: 30,
    image: 'products/medalhao-sonserina.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    house: 'sonserina',
    tags: ['horcrux'],
    synopsis:
      'Réplica em metal do medalhão que Regulus Black trocou na caverna: a serpente em esmeralda no verso e o fecho que abre de verdade. Uma das sete Horcruxes, agora inofensiva.',
  },
  {
    slug: 'diadema-de-rowena-corvinal',
    title: 'Diadema de Rowena Corvinal',
    kind: 'COLLECTIBLE',
    price: 259.9,
    stock: 20,
    image: 'products/diadema-corvinal.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    house: 'corvinal',
    tags: ['horcrux', 'colecionador'],
    synopsis:
      'A tiara perdida por séculos na Sala Precisa, com a inscrição em relevo: "engenho sem medida é o maior tesouro do homem". Réplica em metal com pedra azul, sobre base de exposição.',
  },
  {
    slug: 'taca-de-helga-lufa-lufa',
    title: 'Taça de Helga Lufa-Lufa',
    kind: 'COLLECTIBLE',
    price: 209.9,
    stock: 24,
    image: 'products/taca-lufa-lufa.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    house: 'lufa-lufa',
    tags: ['horcrux'],
    synopsis:
      'A taça de ouro com o texugo gravado, guardada no cofre dos Lestrange sob um feitiço de multiplicação. Réplica em metal dourado de 12 cm, com as duas alças fiéis à original.',
  },
  {
    slug: 'diario-de-tom-riddle',
    title: 'Diário de Tom Riddle',
    kind: 'COLLECTIBLE',
    price: 129.9,
    stock: 42,
    image: 'products/diario-tom-riddle.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    house: 'sonserina',
    character: 'Tom Riddle',
    tags: ['horcrux'],
    synopsis:
      'Caderno preto de capa mole, cinquenta anos de idade e nenhuma palavra escrita, até você escrever. Vem com a marca do dente de basilisco no meio das páginas, como no dia em que Harry acabou com ele.',
    excerpt: 'Nunca confie em nada que pense sozinho se você não pode ver onde ele guarda o cérebro.',
  },
  {
    slug: 'espada-de-godrico-grifinoria',
    title: 'Espada de Godrico Grifinória',
    kind: 'COLLECTIBLE',
    price: 449.9,
    compareAtPrice: 529.9,
    stock: 10,
    image: 'products/espada-grifinoria.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    house: 'grifinoria',
    tags: ['colecionador'],
    synopsis:
      'Lâmina de 86 cm com os rubis no punho e o nome do fundador gravado logo abaixo da guarda. Só se apresenta a um verdadeiro grifinório, e a quem pagar o frete, que neste caso é grátis.',
  },
  {
    slug: 'taca-do-torneio-tribruxo',
    title: 'Taça do Torneio Tribruxo',
    kind: 'COLLECTIBLE',
    price: 269.9,
    stock: 15,
    image: 'products/taca-tribruxo.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    tags: ['colecionador'],
    synopsis:
      'A taça que espera no fim do labirinto, em metal escovado com as três alças e a base larga. Esta não é uma chave de portal, já testamos.',
  },
  {
    slug: 'calice-de-fogo-replica',
    title: 'Cálice de Fogo',
    kind: 'COLLECTIBLE',
    price: 349.9,
    stock: 11,
    image: 'products/calice-de-fogo-replica.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    tags: ['colecionador'],
    synopsis:
      'A taça de madeira tosca que cospe os nomes dos campeões, em réplica de 30 cm com acabamento envelhecido e chama em resina translúcida na boca. Não aceita nomes escritos em guardanapo.',
  },
  {
    slug: 'ovo-de-ouro',
    title: 'Ovo de Ouro do Torneio',
    kind: 'COLLECTIBLE',
    price: 239.9,
    stock: 18,
    image: 'products/ovo-de-ouro.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    synopsis:
      'Réplica do ovo que o dragão guardava, com as dobradiças que abrem e o interior forrado. O grito só sai se você abrir fora da água. Foi assim que o Cedrico contou.',
  },
  {
    slug: 'reliquias-da-morte-pingente',
    title: 'As Relíquias da Morte: pingente',
    kind: 'COLLECTIBLE',
    price: 99.9,
    stock: 65,
    image: 'products/reliquias-da-morte-simbolo.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    tags: ['presente'],
    synopsis:
      'O triângulo, o círculo e a linha reta em prata escovada, no tamanho certo para usar por baixo da camisa. O símbolo que Xenofílio Lovegood usou no casamento e que quase ninguém entendeu na hora.',
  },
  {
    slug: 'bola-de-cristal-adivinhacao',
    title: 'Bola de cristal da aula de Adivinhação',
    kind: 'COLLECTIBLE',
    price: 189.9,
    stock: 28,
    image: 'products/bola-de-cristal.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    character: 'Sibila Trelawney',
    synopsis:
      'Esfera de vidro de 12 cm sobre base de resina trabalhada, igual às da sala da professora Trelawney. Não prevê o futuro; distorce bonito a luz da janela e serve de peso na mesa.',
  },
  {
    slug: 'chapeu-seletor',
    title: 'Chapéu Seletor',
    kind: 'COLLECTIBLE',
    price: 279.9,
    stock: 22,
    image: 'products/chapeu-seletor.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    featured: true,
    tags: ['presente', 'mais-vendido'],
    synopsis:
      'Réplica em feltro envelhecido do chapéu de Godrico Grifinória, com o rasgo que faz as vezes de boca e as rugas todas no lugar certo. Se quiser saber a sua casa antes de comprar, o Chapéu do site atende de graça.',
    excerpt: 'Talvez em Sonserina você encontre seus verdadeiros amigos.',
  },
  {
    slug: 'espectrolentes-de-luna',
    title: 'Espectrolentes de Luna Lovegood',
    kind: 'COLLECTIBLE',
    price: 89.9,
    stock: 50,
    image: 'products/espectrolentes.jpg',
    genre: 'Réplica',
    brand: CINEREPLICAS,
    house: 'corvinal',
    character: 'Luna Lovegood',
    tags: ['presente'],
    synopsis:
      'Os óculos coloridos que revelam bufo-de-chifre-enrugado e, segundo a Luna, também zonzóbulos. Armação em plástico rígido com lentes azul, rosa e amarela sobrepostas.',
  },
  {
    slug: 'guarda-chuva-de-hagrid',
    title: 'Guarda-chuva rosa de Hagrid',
    kind: 'COLLECTIBLE',
    price: 199.9,
    stock: 20,
    image: 'products/guarda-chuva-hagrid.jpg',
    genre: 'Réplica',
    brand: NOBLE,
    character: 'Rúbeo Hagrid',
    tags: ['presente'],
    synopsis:
      'O guarda-chuva rosa que guarda os pedaços da varinha quebrada. Funciona como guarda-chuva de verdade, 105 cm de vareta, e não recomendamos usá-lo para dar rabo de porco em ninguém.',
  },
  {
    slug: 'carta-de-aceitacao-de-hogwarts',
    title: 'Carta de aceitação de Hogwarts personalizada',
    kind: 'COLLECTIBLE',
    price: 79.9,
    stock: 100,
    image: 'products/carta-hogwarts.jpg',
    genre: 'Réplica',
    brand: CINEREPLICAS,
    featured: true,
    tags: ['presente', 'novidade', 'mais-vendido'],
    synopsis:
      'Envelope de pergaminho com selo de lacre nas quatro casas, endereçado com o nome e o endereço de quem vai receber, escritos à mão com pena. Dentro vão a carta da subdiretora e a lista de material escolar.',
    excerpt: 'Temos o prazer de informar que V. Sa. tem uma vaga na Escola de Magia e Bruxaria de Hogwarts.',
  },
  {
    slug: 'sapos-de-chocolate',
    title: 'Sapos de chocolate: caixa com 6',
    kind: 'COLLECTIBLE',
    price: 89.9,
    stock: 120,
    image: 'products/sapo-de-chocolate.jpg',
    genre: 'Doces',
    brand: PALADONE,
    tags: ['presente', 'novidade'],
    synopsis:
      'Seis sapos de chocolate ao leite, cada um na caixa pentagonal com uma figurinha de bruxo famoso dentro. As figurinhas são vinte e quatro no total; a do Dumbledore é a que todo mundo já tem.',
  },
  {
    slug: 'livro-de-pocoes-do-principe',
    title: 'Livro de Poções do Príncipe Mestiço',
    kind: 'COLLECTIBLE',
    price: 159.9,
    stock: 26,
    image: 'products/livro-de-pocoes.jpg',
    genre: 'Réplica',
    brand: CINEREPLICAS,
    character: 'Severo Snape',
    tags: ['presente'],
    synopsis:
      'Réplica do exemplar de "Poções Avançadas" com as anotações do Príncipe rabiscadas nas margens, página por página, incluindo o "sectumsempra, para inimigos" que ninguém deveria ter testado.',
  },
  {
    slug: 'xicara-do-grim',
    title: 'Xícara do Grim: leitura de borra',
    kind: 'COLLECTIBLE',
    price: 119.9,
    stock: 40,
    image: 'products/xicara-do-grim.jpg',
    genre: 'Réplica',
    brand: PALADONE,
    character: 'Sibila Trelawney',
    synopsis:
      'Xícara e pires de porcelana com o cão negro desenhado no fundo, que só aparece quando o chá acaba. O presente perfeito para quem gosta de assustar visita.',
  },
]

const FIGURAS: SeedProduct[] = [
  {
    slug: 'miniatura-do-expresso-de-hogwarts',
    title: 'Miniatura do Expresso de Hogwarts',
    kind: 'FIGURE',
    price: 189.9,
    stock: 28,
    image: 'products/expresso-hogwarts.jpg',
    genre: 'Miniatura',
    brand: NOBLE,
    tags: ['presente'],
    synopsis:
      'A locomotiva vermelha em die-cast na escala 1:64, 22 cm de comprimento, com a placa "Hogwarts Express" e as rodas que giram. Sai da plataforma nove e meia às onze em ponto.',
  },
  {
    slug: 'figura-fenix-fawkes',
    title: 'Fawkes, a fênix: estatueta',
    kind: 'FIGURE',
    price: 279.9,
    stock: 16,
    image: 'products/fenix.jpg',
    genre: 'Miniatura',
    brand: NOBLE,
    character: 'Alvo Dumbledore',
    tags: ['colecionador'],
    synopsis:
      'Estatueta pintada à mão de 30 cm com as penas escarlate e douradas abertas, sobre poleiro de bronze. A ave que chora cura e que carrega quem quer que seja, por mais pesado que esteja.',
  },
  {
    slug: 'figura-rabo-cornea-hungaro',
    title: 'Rabo-Córneo Húngaro: estatueta',
    kind: 'FIGURE',
    price: 349.9,
    stock: 12,
    image: 'products/dragao.jpg',
    genre: 'Miniatura',
    brand: NOBLE,
    tags: ['colecionador'],
    synopsis:
      'O dragão da primeira tarefa do Torneio, em resina pintada à mão, 35 cm de envergadura. Cauda com espinhos, asas membranosas e a boca aberta o suficiente para intimidar a estante.',
  },
  {
    slug: 'miniatura-gabinete-de-dumbledore',
    title: 'Diorama do gabinete de Dumbledore',
    kind: 'FIGURE',
    price: 429.9,
    stock: 8,
    image: 'products/gabinete-dumbledore.jpg',
    genre: 'Miniatura',
    brand: NOBLE,
    character: 'Alvo Dumbledore',
    tags: ['colecionador'],
    synopsis:
      'O gabinete circular em miniatura: a escrivaninha, os instrumentos de prata que soltam fumaça, a penseira no armário e os retratos dos diretores anteriores em molduras de 1 cm. Peça de vitrine.',
  },
  {
    slug: 'bau-de-olho-tonto-moody',
    title: 'Baú de Olho-Tonto Moody',
    kind: 'FIGURE',
    price: 319.9,
    stock: 10,
    image: 'products/bau-de-moody.jpg',
    genre: 'Miniatura',
    brand: NOBLE,
    character: 'Alastor Moody',
    tags: ['colecionador'],
    synopsis:
      'O baú de sete fechaduras em réplica de 25 cm, com as tranquetas funcionando de verdade. Na sétima gaveta não cabe um professor, só chaves, moedas e o que você quiser esconder.',
  },
  {
    slug: 'relogio-do-patio-de-hogwarts',
    title: 'Relógio do pátio de Hogwarts',
    kind: 'FIGURE',
    price: 259.9,
    stock: 14,
    image: 'products/relogio-hogwarts.jpg',
    genre: 'Miniatura',
    brand: NOBLE,
    synopsis:
      'O grande relógio de pêndulo do pátio interno, em miniatura de 28 cm com o mecanismo à vista e os ponteiros que andam. Foi ele que marcou as três voltas do vira-tempo.',
  },
  {
    slug: 'ampulhetas-das-casas',
    title: 'Ampulhetas da Taça das Casas',
    kind: 'FIGURE',
    price: 389.9,
    stock: 9,
    image: 'products/ampulhetas-das-casas.jpg',
    genre: 'Miniatura',
    brand: NOBLE,
    featured: true,
    tags: ['colecionador', 'presente'],
    synopsis:
      'As quatro ampulhetas do Salão de Entrada em miniatura, com rubis, esmeraldas, safiras e topázios de verdade em vidro colorido. Vêm cheias por igual; quem sobe e quem desce é problema seu.',
  },
  {
    slug: 'boneco-colecionavel-harry-potter',
    title: 'Boneco colecionável Harry Potter',
    kind: 'FIGURE',
    price: 119.9,
    stock: 65,
    image: 'products/aparelhos-magicos.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    house: 'grifinoria',
    character: 'Harry Potter',
    tags: ['presente'],
    synopsis:
      'Figura de vinil de 10 cm, cabeça grande e uniforme de Hogwarts, na caixa com janela transparente. Fica bem na prateleira, ao lado dos sete volumes.',
  },
  {
    slug: 'boneco-colecionavel-hermione',
    title: 'Boneco colecionável Hermione Granger',
    kind: 'FIGURE',
    price: 119.9,
    stock: 58,
    image: 'products/aparelhos-magicos-2.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    house: 'grifinoria',
    character: 'Hermione Granger',
    tags: ['presente'],
    synopsis:
      'A Hermione de vinil com o livro debaixo do braço e a varinha na mão. Dez centímetros, caixa com janela, e a expressão de quem já leu o capítulo que você ainda vai ler.',
  },
  {
    slug: 'boneco-colecionavel-dobby',
    title: 'Boneco colecionável Dobby',
    kind: 'FIGURE',
    price: 129.9,
    stock: 44,
    image: 'products/aparelhos-magicos-3.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    character: 'Dobby',
    tags: ['presente', 'mais-vendido'],
    synopsis:
      'O elfo livre em vinil, com a meia na mão e as orelhas maiores que a cabeça. Dobby não tem dono. Dobby tem uma caixa com janela transparente e 10 cm de altura.',
  },
  {
    slug: 'boneco-colecionavel-dumbledore',
    title: 'Boneco colecionável Alvo Dumbledore',
    kind: 'FIGURE',
    price: 129.9,
    stock: 40,
    image: 'products/aparelhos-magicos-4.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    character: 'Alvo Dumbledore',
    synopsis:
      'Barba até a cintura, óculos de meia-lua e a varinha em riste. Figura de vinil de 10 cm, a mais pedida da linha depois do Dobby.',
  },
  {
    slug: 'boneco-colecionavel-snape',
    title: 'Boneco colecionável Severo Snape',
    kind: 'FIGURE',
    price: 129.9,
    stock: 38,
    image: 'products/aparelhos-magicos-5.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    house: 'sonserina',
    character: 'Severo Snape',
    synopsis:
      'De preto dos pés à cabeça, com o frasco de poção na mão. A cara de poucos amigos foi esculpida com capricho, dá para reconhecer de longe na estante.',
  },
  {
    slug: 'boneco-colecionavel-hagrid',
    title: 'Boneco colecionável Hagrid: tamanho grande',
    kind: 'FIGURE',
    price: 229.9,
    stock: 22,
    image: 'products/aparelhos-magicos-6.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    character: 'Rúbeo Hagrid',
    tags: ['colecionador'],
    synopsis:
      'A versão de 25 cm, três vezes o tamanho dos outros da linha, como manda a proporção. Casacão de pele, barba fechada e a lanterna na mão.',
  },
  {
    slug: 'boneco-colecionavel-voldemort',
    title: 'Boneco colecionável Lorde Voldemort',
    kind: 'FIGURE',
    price: 129.9,
    stock: 34,
    image: 'products/aparelhos-magicos-7.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    house: 'sonserina',
    character: 'Lorde Voldemort',
    synopsis:
      'Sem nariz, de manto preto e com Nagini enrolada no pé da base. Figura de vinil de 10 cm, a única da linha que dá um leve arrepio na prateleira.',
  },
  {
    slug: 'boneco-colecionavel-luna',
    title: 'Boneco colecionável Luna Lovegood',
    kind: 'FIGURE',
    price: 119.9,
    stock: 36,
    image: 'products/aparelhos-magicos-8.jpg',
    genre: 'Boneco',
    brand: FUNKO,
    house: 'corvinal',
    character: 'Luna Lovegood',
    synopsis:
      'Com os espectrolentes no rosto e o exemplar do Pasquim de cabeça para baixo. Dez centímetros de vinil e a serenidade de quem nunca se importou com o que os outros acham.',
  },
]

// ===== Vestuário e acessórios =====

const VESTUARIO: SeedProduct[] = [
  {
    slug: 'manto-de-hogwarts',
    title: 'Manto de Hogwarts',
    kind: 'APPAREL',
    price: 349.9,
    compareAtPrice: 399.9,
    stock: 40,
    image: 'products/manto-hogwarts.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    featured: true,
    tags: ['mais-vendido', 'presente'],
    synopsis:
      'Manto preto de gabardine com forro nas cores da casa, brasão bordado no peito e capuz. Tamanhos P ao GG, com o comprimento que os alunos usam no inverno escocês. A casa é escolhida no fechamento do pedido.',
  },
  {
    slug: 'uniforme-de-quadribol',
    title: 'Uniforme de quadribol',
    kind: 'APPAREL',
    price: 429.9,
    stock: 24,
    image: 'products/uniforme-quadribol.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    tags: ['quadribol'],
    synopsis:
      'Túnica, capa, caneleiras e luvas de couro sintético, com o número nas costas. O mesmo corte que a Grifinória usou no campeonato de 1994. E sim, dá para jogar de verdade nele.',
  },
  {
    slug: 'cachecol-da-sua-casa',
    title: 'Cachecol da sua casa',
    kind: 'APPAREL',
    price: 149.9,
    stock: 90,
    image: 'products/estandarte-grifinoria.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    featured: true,
    tags: ['presente', 'mais-vendido'],
    synopsis:
      'Cachecol de lã de 180 cm nas listras da casa, com franjas nas pontas e o brasão bordado numa das extremidades. Escolha a casa no fechamento do pedido, ou deixe o Chapéu Seletor do site escolher por você.',
  },
  {
    slug: 'sueter-da-casa',
    title: 'Suéter da casa',
    kind: 'APPAREL',
    price: 279.9,
    stock: 55,
    image: 'products/estandarte-corvinal.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    tags: ['presente'],
    synopsis:
      'Suéter de tricô com gola em V e as duas listras da casa no punho e no colarinho. É o de baixo do uniforme, que virou peça de inverno por conta própria.',
  },
  {
    slug: 'gravata-da-casa',
    title: 'Gravata da casa',
    kind: 'APPAREL',
    price: 89.9,
    stock: 110,
    image: 'products/estandarte-sonserina.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    tags: ['presente'],
    synopsis:
      'Gravata listrada em poliéster acetinado, 145 cm, no padrão dos alunos do sexto ano. Vem com o nó pronto para ajustar, porque ninguém aprende a dar nó por causa de uma escola de magia.',
  },
  {
    slug: 'traje-de-gala-do-baile-de-inverno',
    title: 'Traje de gala do Baile de Inverno',
    kind: 'APPAREL',
    price: 599.9,
    stock: 12,
    image: 'products/vestido-baile.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    tags: ['colecionador'],
    synopsis:
      'O vestido azul-claro de chiffon do Baile de Inverno, com o corpete bordado e a saia em camadas. Feito sob medida, com quatro semanas de prazo. Vale a espera e a foto.',
  },
  {
    slug: 'vestido-de-beauxbatons',
    title: 'Uniforme de Beauxbatons',
    kind: 'APPAREL',
    price: 399.9,
    stock: 15,
    image: 'products/vestido-beauxbatons.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    synopsis:
      'O azul-seda da delegação francesa, com o chapéu combinando. Elegante o bastante para fazer o Salão Principal inteiro parar quando a porta se abre.',
  },
  {
    slug: 'manto-de-comensal-da-morte',
    title: 'Manto de Comensal da Morte',
    kind: 'APPAREL',
    price: 449.9,
    stock: 18,
    image: 'products/traje-comensal.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'sonserina',
    tags: ['colecionador'],
    synopsis:
      'Manto preto de tecido pesado com capuz alto e máscara prateada de metal frio. A peça mais bem acabada da linha, e a que a gente não recomenda usar em festa de escola.',
  },
  {
    slug: 'traje-de-luna-lovegood',
    title: 'Traje de Luna Lovegood',
    kind: 'APPAREL',
    price: 329.9,
    stock: 20,
    image: 'products/traje-luna.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'corvinal',
    character: 'Luna Lovegood',
    synopsis:
      'O vestido estampado com os rabanetes de brinco combinando e a capa da Corvinal por cima. Um figurino que só faz sentido quando a pessoa não está nem aí, que é justamente o ponto.',
  },
  {
    slug: 'traje-de-draco-malfoy',
    title: 'Traje de Draco Malfoy',
    kind: 'APPAREL',
    price: 359.9,
    stock: 18,
    image: 'products/traje-draco.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'sonserina',
    character: 'Draco Malfoy',
    synopsis:
      'Terno escuro sob o manto da Sonserina, com o colarinho engomado e o alfinete de prata. O uniforme de quem tem sobrenome antes de ter nota.',
  },
  {
    slug: 'traje-de-severo-snape',
    title: 'Sobrecasaca de Severo Snape',
    kind: 'APPAREL',
    price: 469.9,
    stock: 14,
    image: 'products/traje-snape.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'sonserina',
    character: 'Severo Snape',
    tags: ['colecionador'],
    synopsis:
      'A sobrecasaca preta de gola alta com os quarenta botões forrados, um por um, do jeito que o figurino original foi feito. É a peça de vestuário mais trabalhosa que vendemos.',
  },
  {
    slug: 'traje-de-sirius-black',
    title: 'Casaco de Sirius Black',
    kind: 'APPAREL',
    price: 419.9,
    stock: 13,
    image: 'products/traje-sirius.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'grifinoria',
    character: 'Sirius Black',
    synopsis:
      'Sobretudo longo em tecido envelhecido, com os punhos gastos de propósito e o forro em cetim. A roupa de quem passou doze anos em Azkaban e ainda assim tem estilo.',
  },
  {
    slug: 'traje-de-bellatrix-lestrange',
    title: 'Vestido de Bellatrix Lestrange',
    kind: 'APPAREL',
    price: 479.9,
    stock: 11,
    image: 'products/traje-bellatrix.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'sonserina',
    character: 'Bellatrix Lestrange',
    tags: ['colecionador'],
    synopsis:
      'Vestido preto de renda rasgada com corpete de couro e as mangas em babados desiguais. Feito para parecer que atravessou uma batalha, porque atravessou.',
  },
  {
    slug: 'traje-de-gilderoy-lockhart',
    title: 'Traje de Gilderoy Lockhart',
    kind: 'APPAREL',
    price: 389.9,
    stock: 16,
    image: 'products/traje-lockhart.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    character: 'Gilderoy Lockhart',
    synopsis:
      'Túnica lilás com bordado dourado e a capa combinando, do professor mais fotografado e menos competente que Hogwarts já teve. Vem com autógrafo impresso. Ele insistiu.',
  },
  {
    slug: 'uniforme-de-cho-chang',
    title: 'Uniforme de Cho Chang',
    kind: 'APPAREL',
    price: 319.9,
    stock: 19,
    image: 'products/traje-cho.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'corvinal',
    character: 'Cho Chang',
    synopsis:
      'Saia plissada, meia até o joelho e a capa azul e bronze da Corvinal. O uniforme completo da apanhadora do time da casa.',
  },
  {
    slug: 'manto-de-lorde-voldemort',
    title: 'Manto de Lorde Voldemort',
    kind: 'APPAREL',
    price: 529.9,
    stock: 9,
    image: 'products/traje-voldemort.jpg',
    genre: 'Vestuário',
    brand: CINEREPLICAS,
    house: 'sonserina',
    character: 'Lorde Voldemort',
    tags: ['colecionador'],
    synopsis:
      'Manto cinza-esverdeado de tecido enrugado, com a gola alta e as mangas largas. Não tem brasão, não tem cor de casa: quem usa isso já se acha acima das quatro.',
  },
]

// ===== Papelaria =====

const PAPELARIA: SeedProduct[] = [
  {
    slug: 'caderno-de-desenho-de-hogwarts',
    title: 'Caderno de desenho de Hogwarts',
    kind: 'STATIONERY',
    price: 79.9,
    stock: 90,
    image: 'products/cadernos.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    featured: true,
    tags: ['novidade', 'presente'],
    synopsis:
      'Sketchbook de capa dura com 120 folhas de papel 180 g/m², liso, que aguenta grafite, nanquim e aquarela leve. Costura aparente para abrir em 180 graus e desenhar na página dupla inteira.',
  },
  {
    slug: 'caderno-mapa-do-maroto',
    title: 'Caderno Mapa do Maroto',
    kind: 'STATIONERY',
    price: 69.9,
    stock: 85,
    image: 'products/aparelhos-magicos-2.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    tags: ['presente', 'mais-vendido'],
    synopsis:
      'Caderno pautado A5 com o mapa impresso na capa e nas guardas, elástico de fechamento e marcador de fita. Juro solenemente não fazer nada de bom nestas 160 páginas.',
    excerpt: 'Malfeito, feito.',
  },
  {
    slug: 'agenda-de-hogwarts',
    title: 'Agenda escolar de Hogwarts',
    kind: 'STATIONERY',
    price: 99.9,
    stock: 60,
    image: 'products/aparelhos-magicos-3.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    tags: ['novidade'],
    synopsis:
      'Agenda de doze meses com o calendário letivo do castelo: início das aulas em 1º de setembro, jogos de quadribol marcados e as datas dos feriados bruxos. Capa dura, dois marcadores.',
  },
  {
    slug: 'pena-e-tinteiro',
    title: 'Pena e tinteiro',
    kind: 'STATIONERY',
    price: 119.9,
    stock: 70,
    image: 'products/pena-e-tinteiro.jpg',
    genre: 'Papelaria',
    brand: NOBLE,
    featured: true,
    tags: ['presente'],
    synopsis:
      'Pena natural de ganso com ponta de metal substituível e tinteiro de vidro com 30 ml de tinta preta. Escrever com ela é mais devagar e muito mais bonito, e é como se escreve em Hogwarts.',
  },
  {
    slug: 'pena-de-luxo-italiana',
    title: 'Pena de luxo com estojo',
    kind: 'STATIONERY',
    price: 189.9,
    stock: 34,
    image: 'products/pena-italiana.jpg',
    genre: 'Papelaria',
    brand: NOBLE,
    tags: ['colecionador', 'presente'],
    synopsis:
      'Pena longa em estojo de madeira forrado, com três pontas de troca, tinteiro de cerâmica e um mata-borrão. O conjunto que se dá de presente de formatura.',
  },
  {
    slug: 'marcadores-magneticos-das-casas',
    title: 'Marcadores magnéticos das quatro casas',
    kind: 'STATIONERY',
    price: 49.9,
    stock: 140,
    image: 'products/ampulhetas-das-casas.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Kit com quatro marcadores magnéticos, um por casa, que dobram sobre a página e não caem quando o livro fecha. O jeito civilizado de marcar onde parou, em vez de dobrar a ponta da folha.',
  },
  {
    slug: 'caneta-varinha',
    title: 'Caneta em forma de varinha',
    kind: 'STATIONERY',
    price: 59.9,
    stock: 130,
    image: 'products/varinha-lumos.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Esferográfica de 25 cm com o corpo esculpido como varinha e carga preta comum, dessas que se acham em qualquer papelaria. Serve para assinar documentos com bem mais cerimônia do que o necessário.',
  },
  {
    slug: 'papel-de-carta-de-hogwarts',
    title: 'Papel de carta e envelopes de Hogwarts',
    kind: 'STATIONERY',
    price: 74.9,
    stock: 76,
    image: 'products/carta-hogwarts.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Vinte folhas de papel pergaminho com o timbre da escola, vinte envelopes forrados e um bastão de lacre com o carimbo do brasão. Uma carta escrita nisso não vai para a caixa de spam.',
  },
  {
    slug: 'adesivos-do-mundo-bruxo',
    title: 'Cartela de adesivos do mundo bruxo',
    kind: 'STATIONERY',
    price: 34.9,
    stock: 200,
    image: 'products/aparelhos-magicos-4.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Cento e vinte adesivos em vinil resistente: brasões, feitiços, criaturas e o horário do Expresso. Colam em notebook, garrafa e caderno, e saem sem deixar cola.',
  },
  {
    slug: 'estojo-de-hogwarts',
    title: 'Estojo escolar de Hogwarts',
    kind: 'STATIONERY',
    price: 89.9,
    stock: 68,
    image: 'products/aparelhos-magicos-5.jpg',
    genre: 'Papelaria',
    brand: PALADONE,
    synopsis:
      'Estojo de lona encerada com fecho de fivela, dois compartimentos e o brasão em serigrafia. Cabe pena, tinteiro e a caneta-varinha ao mesmo tempo, o que já é bastante.',
  },
]

// ===== Jogos e blocos =====

const JOGOS: SeedProduct[] = [
  {
    slug: 'lego-castelo-de-hogwarts',
    title: 'LEGO Castelo de Hogwarts: 6.020 peças',
    kind: 'GAME',
    price: 2899.9,
    compareAtPrice: 3299.9,
    stock: 6,
    image: 'products/lego-castelo-hogwarts.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    featured: true,
    tags: ['colecionador', 'presente'],
    synopsis:
      'O castelo inteiro em microescala, com o Salão Principal, a Câmara Secreta, o Salgueiro Lutador e a cabana do Hagrid. Seis mil e vinte peças, quatro minifiguras dos fundadores e 27 microfiguras. O maior conjunto que vendemos, e o que mais demora a montar.',
  },
  {
    slug: 'lego-castelo-e-terrenos',
    title: 'LEGO Castelo e Terrenos de Hogwarts',
    kind: 'GAME',
    price: 1399.9,
    stock: 10,
    image: 'products/lego-castelo-e-terrenos.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    tags: ['presente'],
    synopsis:
      'A versão de exposição do castelo com o lago, a ponte de madeira e o campo de quadribol ao redor. Montado, ocupa meio metro de prateleira e ganha luz própria à noite.',
  },
  {
    slug: 'lego-camara-secreta',
    title: 'LEGO A Câmara Secreta',
    kind: 'GAME',
    price: 799.9,
    stock: 14,
    image: 'products/lego-camara-secreta.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    synopsis:
      'A câmara com a estátua de Salazar, o basilisco articulado de 60 cm e o diário no chão. Dez minifiguras, incluindo a Gina, o Tom Riddle e um Fawkes que voa em suporte transparente.',
  },
  {
    slug: 'lego-beco-diagonal',
    title: 'LEGO Beco Diagonal',
    kind: 'GAME',
    price: 2199.9,
    stock: 7,
    image: 'products/lego-beco-diagonal.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    tags: ['colecionador'],
    synopsis:
      'Quatro fachadas que se encaixam lado a lado: Olivaras, Gemialidades Weasley, Floreios e Borrões e a sorveteria. Cinco mil peças e catorze minifiguras: a rua inteira em cima da mesa.',
  },
  {
    slug: 'lego-bau-magico-de-hogwarts',
    title: 'LEGO Baú Mágico de Hogwarts',
    kind: 'GAME',
    price: 649.9,
    stock: 20,
    image: 'products/lego-bau-magico.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    tags: ['presente'],
    synopsis:
      'Um baú que abre em três cenários diferentes conforme a casa escolhida, com peças para trocar a decoração. Fecha e vira objeto de estante, a ideia mais engenhosa da linha.',
  },
  {
    slug: 'lego-erro-da-pocao-polissuco',
    title: 'LEGO O Erro da Poção Polissuco',
    kind: 'GAME',
    price: 299.9,
    stock: 30,
    image: 'products/lego-erro-da-pocao.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    synopsis:
      'O banheiro da Murta que Geme com o caldeirão fervendo e a Hermione a meio caminho de virar gato. Duzentas e dezessete peças, boa porta de entrada para a linha.',
  },
  {
    slug: 'lego-xadrez-de-bruxo',
    title: 'LEGO Xadrez de Bruxo',
    kind: 'GAME',
    price: 449.9,
    stock: 24,
    image: 'products/lego-xadrez-de-bruxo.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    featured: true,
    tags: ['presente'],
    synopsis:
      'O tabuleiro gigante da última prova da Pedra Filosofal, com as peças brancas e pretas montáveis. Dá para jogar xadrez de verdade nele, sem que as peças se destruam quando são capturadas.',
  },
  {
    slug: 'lego-icones-de-hogwarts',
    title: 'LEGO Ícones de Hogwarts: coleção de colecionador',
    kind: 'GAME',
    price: 899.9,
    stock: 12,
    image: 'products/lego-icones-de-hogwarts.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    tags: ['colecionador'],
    synopsis:
      'A varinha do Harry, o vira-tempo, os óculos e a carta de aceitação, todos montáveis e sobre placas com o nome gravado. Uma vitrine inteira dentro de uma caixa.',
  },
  {
    slug: 'lego-edwiges',
    title: 'LEGO Edwiges',
    kind: 'GAME',
    price: 349.9,
    stock: 26,
    image: 'products/lego-edwiges.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    character: 'Edwiges',
    tags: ['presente'],
    synopsis:
      'A coruja-das-neves em escala grande, com as asas articuladas que batem quando se gira a alavanca da base, e a carta de Hogwarts presa nas garras.',
  },
  {
    slug: 'lego-expresso-de-hogwarts',
    title: 'LEGO Expresso de Hogwarts: edição colecionador',
    kind: 'GAME',
    price: 1699.9,
    stock: 8,
    image: 'products/lego-expresso-de-hogwarts.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    tags: ['colecionador'],
    synopsis:
      'A locomotiva e o vagão em escala grande, com a plataforma nove e meia, a parede que atravessa e o carrinho de doces. Cinco mil peças e cinco minifiguras.',
  },
  {
    slug: 'lego-carruagem-de-hogwarts',
    title: 'LEGO Carruagem de Hogwarts e Testrálios',
    kind: 'GAME',
    price: 279.9,
    stock: 32,
    image: 'products/lego-carruagem.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    synopsis:
      'A carruagem preta puxada por dois testrálios articulados, que só quem já viu a morte enxerga, mas que na caixa vêm sempre. Cento e vinte e uma peças.',
  },
  {
    slug: 'lego-torre-de-astronomia',
    title: 'LEGO Torre de Astronomia de Hogwarts',
    kind: 'GAME',
    price: 899.9,
    stock: 15,
    image: 'products/lego-torre-de-astronomia.jpg',
    genre: 'Blocos de montar',
    brand: LEGO,
    synopsis:
      'A torre em quatro andares, do dormitório da Corvinal ao topo aberto onde a aula de Astronomia acontece. Novecentas e setenta e uma peças e oito minifiguras.',
  },
  {
    slug: 'quebra-cabeca-do-castelo',
    title: 'Quebra-cabeça do castelo: 1.000 peças',
    kind: 'GAME',
    price: 129.9,
    stock: 48,
    image: 'products/loja-de-magia.jpg',
    genre: 'Quebra-cabeça',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Mil peças de papelão de 2 mm com acabamento fosco, formando o castelo visto do lago ao anoitecer. Montado dá 68 por 48 cm, cabe numa moldura comum.',
  },
  {
    slug: 'jogo-de-tabuleiro-batalha-por-hogwarts',
    title: 'Batalha por Hogwarts: jogo de tabuleiro',
    kind: 'GAME',
    price: 349.9,
    compareAtPrice: 399.9,
    stock: 28,
    image: 'products/livros-magicos.jpg',
    genre: 'Tabuleiro',
    brand: PALADONE,
    featured: true,
    tags: ['presente', 'novidade'],
    synopsis:
      'Jogo cooperativo de construção de baralho para dois a quatro jogadores, em sete caixas, uma por ano da saga, que vão abrindo cartas novas conforme vocês avançam. Uma partida leva quarenta minutos; a campanha inteira, meses.',
  },
  {
    slug: 'xadrez-de-bruxo-de-luxo',
    title: 'Xadrez de bruxo de luxo',
    kind: 'GAME',
    price: 599.9,
    stock: 14,
    image: 'products/aparelhos-magicos-6.jpg',
    genre: 'Tabuleiro',
    brand: NOBLE,
    tags: ['colecionador'],
    synopsis:
      'Tabuleiro de 50 cm em resina imitando pedra, com as trinta e duas peças esculpidas no estilo da câmara subterrânea. As peças não se movem sozinhas nem se despedaçam, o que é uma vantagem.',
  },
]

// ===== Casa e decoração =====

const CASA: SeedProduct[] = [
  {
    slug: 'caneca-mapa-do-maroto',
    title: 'Caneca Mapa do Maroto: muda com o calor',
    kind: 'HOME',
    price: 79.9,
    stock: 120,
    image: 'products/xicara-do-grim.jpg',
    genre: 'Cozinha',
    brand: PALADONE,
    featured: true,
    tags: ['mais-vendido', 'presente'],
    synopsis:
      'Caneca de cerâmica de 350 ml com o mapa impresso em volta. Com a bebida quente, as pegadas aparecem, e somem de novo quando a caneca esfria. Juro solenemente não fazer nada de bom antes do café.',
  },
  {
    slug: 'caneca-da-sua-casa',
    title: 'Caneca da sua casa',
    kind: 'HOME',
    price: 59.9,
    stock: 150,
    image: 'products/estandarte-lufa-lufa.jpg',
    genre: 'Cozinha',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Caneca de 350 ml com o brasão de um lado e o lema da casa do outro, em cerâmica esmaltada que aguenta lava-louças. A cor vem da casa escolhida no pedido.',
  },
  {
    slug: 'estandarte-da-grifinoria',
    title: 'Estandarte da Grifinória',
    kind: 'HOME',
    price: 139.9,
    stock: 40,
    image: 'products/estandarte-grifinoria.jpg',
    genre: 'Decoração',
    brand: CINEREPLICAS,
    house: 'grifinoria',
    tags: ['casa'],
    synopsis:
      'Bandeira de tecido de 76 por 122 cm com o leão bordado sobre o vermelho e ouro, com bainha superior para pendurar em vareta. A mesma que cobre as paredes do Salão Principal em dia de final.',
  },
  {
    slug: 'estandarte-da-sonserina',
    title: 'Estandarte da Sonserina',
    kind: 'HOME',
    price: 139.9,
    stock: 40,
    image: 'products/estandarte-sonserina.jpg',
    genre: 'Decoração',
    brand: CINEREPLICAS,
    house: 'sonserina',
    tags: ['casa'],
    synopsis:
      'Bandeira de tecido de 76 por 122 cm com a serpente sobre o verde e prata. Fica bem atrás da escrivaninha e melhor ainda na parede do quarto de quem tem orgulho de ser da casa mais mal falada.',
  },
  {
    slug: 'estandarte-da-corvinal',
    title: 'Estandarte da Corvinal',
    kind: 'HOME',
    price: 139.9,
    stock: 40,
    image: 'products/estandarte-corvinal.jpg',
    genre: 'Decoração',
    brand: CINEREPLICAS,
    house: 'corvinal',
    tags: ['casa'],
    synopsis:
      'Bandeira de tecido de 76 por 122 cm com a águia sobre o azul e bronze. A cor exata é a do livro, não a do filme. E sim, sabemos que essa discussão nunca termina.',
  },
  {
    slug: 'estandarte-da-lufa-lufa',
    title: 'Estandarte da Lufa-Lufa',
    kind: 'HOME',
    price: 139.9,
    stock: 40,
    image: 'products/estandarte-lufa-lufa.jpg',
    genre: 'Decoração',
    brand: CINEREPLICAS,
    house: 'lufa-lufa',
    tags: ['casa'],
    synopsis:
      'Bandeira de tecido de 76 por 122 cm com o texugo sobre o amarelo e preto. A casa que ninguém escolhe por status e que todo mundo acaba respeitando no sétimo livro.',
  },
  {
    slug: 'luminaria-vira-tempo',
    title: 'Luminária Vira-Tempo',
    kind: 'HOME',
    price: 249.9,
    stock: 22,
    image: 'products/vira-tempo-caixa.jpg',
    genre: 'Iluminação',
    brand: PALADONE,
    tags: ['novidade', 'presente'],
    synopsis:
      'Abajur de mesa com os aros dourados girando devagar em torno da lâmpada quente, projetando o desenho no teto. Luz baixa o suficiente para ler na cama.',
  },
  {
    slug: 'luminaria-do-castelo',
    title: 'Luminária do castelo',
    kind: 'HOME',
    price: 199.9,
    stock: 26,
    image: 'products/gabinete-dumbledore.jpg',
    genre: 'Iluminação',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'O contorno do castelo recortado em acrílico, iluminado por baixo em âmbar. Ligada na tomada ou em três pilhas, e com um botão que troca a cor para a da sua casa.',
  },
  {
    slug: 'almofada-da-casa',
    title: 'Almofada da casa',
    kind: 'HOME',
    price: 119.9,
    stock: 60,
    image: 'products/manto-hogwarts.jpg',
    genre: 'Decoração',
    brand: CINEREPLICAS,
    tags: ['presente'],
    synopsis:
      'Almofada de 45 por 45 cm com capa removível em veludo, brasão bordado à frente e listras da casa atrás. Vem com o enchimento; a casa escolhe você.',
  },
  {
    slug: 'quadro-do-expresso',
    title: 'Quadro do Expresso de Hogwarts',
    kind: 'HOME',
    price: 179.9,
    stock: 30,
    image: 'products/expresso-hogwarts.jpg',
    genre: 'Decoração',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Impressão em papel de algodão 300 g com moldura de madeira escura, 40 por 60 cm: a locomotiva atravessando o viaduto na neblina da manhã.',
  },
  {
    slug: 'relogio-de-parede-de-hogwarts',
    title: 'Relógio de parede de Hogwarts',
    kind: 'HOME',
    price: 209.9,
    stock: 24,
    image: 'products/relogio-hogwarts.jpg',
    genre: 'Decoração',
    brand: PALADONE,
    synopsis:
      'Trinta centímetros de diâmetro, ponteiros em latão e os números romanos do relógio do pátio. Mecanismo silencioso, não faz tique-taque na madrugada.',
  },
  {
    slug: 'copo-de-cerveja-amanteigada',
    title: 'Caneco de cerveja amanteigada',
    kind: 'HOME',
    price: 99.9,
    stock: 80,
    image: 'products/canudos.jpg',
    genre: 'Cozinha',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Caneco de vidro grosso de 500 ml com alça e a etiqueta em relevo, igual aos do Três Vassouras. Vem com a receita da bebida quente impressa na caixa.',
  },
  {
    slug: 'jogo-de-pratos-do-salao-principal',
    title: 'Jogo de pratos do Salão Principal',
    kind: 'HOME',
    price: 389.9,
    stock: 18,
    image: 'products/aparelhos-magicos-7.jpg',
    genre: 'Cozinha',
    brand: PALADONE,
    tags: ['novidade'],
    synopsis:
      'Quatro pratos rasos, quatro fundos e quatro de sobremesa em porcelana branca com filete dourado e o brasão discreto na borda. Não se enchem sozinhos, mas fazem um bom jantar.',
  },
  {
    slug: 'tapete-das-quatro-casas',
    title: 'Tapete das quatro casas',
    kind: 'HOME',
    price: 299.9,
    stock: 16,
    image: 'products/ampulhetas-das-casas.jpg',
    genre: 'Decoração',
    brand: CINEREPLICAS,
    tags: ['novidade'],
    synopsis:
      'Tapete redondo de 120 cm com os quatro brasões dispostos em quadrantes, em fio antialérgico e base antiderrapante. O chão da sala vira o Salão de Entrada.',
  },
  {
    slug: 'mochila-de-hogwarts',
    title: 'Mochila de Hogwarts',
    kind: 'ACCESSORY',
    price: 279.9,
    stock: 45,
    image: 'products/bau-de-moody.jpg',
    genre: 'Acessório',
    brand: CINEREPLICAS,
    featured: true,
    tags: ['presente', 'novidade'],
    synopsis:
      'Mochila de lona encerada com fivelas de metal, compartimento para notebook de 15 polegadas e o brasão em couro sintético na frente. Vinte e cinco litros, cabe a semana toda de aula.',
  },
  {
    slug: 'chaveiro-da-sua-casa',
    title: 'Chaveiro da sua casa',
    kind: 'ACCESSORY',
    price: 39.9,
    stock: 180,
    image: 'products/aparelhos-magicos-8.jpg',
    genre: 'Acessório',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Brasão em metal esmaltado de 4 cm com argola reforçada. É o presente barato que sempre funciona, e o único produto da loja que cabe no bolso da calça.',
  },
  {
    slug: 'colar-do-pomo-de-ouro',
    title: 'Colar do Pomo de Ouro',
    kind: 'ACCESSORY',
    price: 129.9,
    stock: 70,
    image: 'products/ovo-de-ouro.jpg',
    genre: 'Joia',
    brand: NOBLE,
    tags: ['quadribol', 'presente'],
    synopsis:
      'A bolinha dourada com as asas articuladas que se abrem e fecham, presa numa corrente de 45 cm. Abre ao meio e guarda uma foto lá dentro, como no fim do sétimo livro.',
  },
  {
    slug: 'broche-das-casas',
    title: 'Conjunto de broches das quatro casas',
    kind: 'ACCESSORY',
    price: 69.9,
    stock: 95,
    image: 'products/reliquias-da-morte-simbolo.jpg',
    genre: 'Acessório',
    brand: PALADONE,
    tags: ['presente'],
    synopsis:
      'Quatro broches de metal esmaltado com fecho borboleta, um por casa, na cartela de colecionador. Para a lapela, a mochila ou a jaqueta jeans.',
  },
]

export const CATALOG: SeedProduct[] = [
  ...SAGA,
  ...CAIXAS,
  ...EDICOES,
  ...COMPLEMENTARES,
  ...VARINHAS,
  ...COLECIONAVEIS,
  ...FIGURAS,
  ...VESTUARIO,
  ...PAPELARIA,
  ...JOGOS,
  ...CASA,
]
